calibration_date: 2022-07-15
sensors:
  camera-1:
    intrinsic: 'camera-1.yaml'
    extrinsic: 
      lidar-1: ['camera-1', 'lidar-1'] 
      body-1: ['camera-1', 'body-1']
  
  camera-2:
    intrinsic: 'camera-2.yaml'
    extrinsic: 
      lidar-1: ['camera-2', 'lidar-1']
  
  lidar-1:
    intrinsic: 'lidar-1.txt'
    extrinsic: 
      camera-1: ['lidar-1', 'camera-1']
      camera-2: ['lidar-1', 'camera-2']
      lidar-2: ['lidar-1', 'lidar-2']
      body-1: ['lidar-1', 'body-1']
      imu-1: ['lidar-1', 'imu-1']
      imu-2: ['lidar-1', 'imu-2']
  
  lidar-2:
    intrinsic: ''
    extrinsic: 
      lidar-1: ['lidar-2', 'lidar-1']
     
  imu-1:
    intrinsic: ''
    extrinsic:
      lidar-1: ['imu-1', 'lidar-1']
  
  imu-2:
    intrinsic: ''
    extrinsic:
      lidar-1: ['imu-2', 'lidar-1']
  
  body-1: 
    intrinsic: ''
    extrinsic: 
      camera-1: ['body-1', 'camera-1']
