calibration_date: 2023-03-22
sensors:
  camera-1:
    intrinsic: 'camera-1.yaml'
    extrinsic:
      lidar-1: ['camera-1', 'lidar-1']
      body-1: ['camera-1', 'body-1']
    
  lidar-1: 
    intrinsic: 'lidar-1.yaml'
    extrinsic:
      camera-1: ['lidar-1', 'camera-1']
      imu-1: ['lidar-1', 'imu-1']
      body-1: ['lidar-1', 'body-1']

  imu-1:
    intrinsic: ''
    extrinsic:
      lidar-1: ['imu-1', 'lidar-1']

