calibration_date: 2023-01-09
sensors:
  camera-1:
    intrinsic: 'camera-1.yaml'
    extrinsic: 
      lidar-1: ['camera-1', 'lidar-1']
      
  camera-2:
    intrinsic: 'camera-2.yaml'
    extrinsic:
      lidar-1: ['camera-2', 'lidar-1']

  camera-3:
    intrinsic: 'camera-3.yaml'
    extrinsic:
      lidar-1: ['camera-3', 'lidar-1']
      
  lidar-1: 
    intrinsic: 'lidar-1.txt'
    extrinsic:
      camera-1: ['lidar-1', 'camera-1']
      camera-2: ['lidar-1', 'camera-2']
      camera-3: ['lidar-1', 'camera-3']
      body-1: ['lidar-1', 'body-1']

  
