calibration_date: 2023-03-22
sensors:
  camera-1:
    intrinsic: 'camera-1.yaml'
    extrinsic: 
      lidar-1: ['camera-1', 'lidar-1'] 
      body-1: ['camera-1', 'body-1']
      body-2: ['camera-1', 'body-2']
  
  lidar-1:
    intrinsic: ''
    extrinsic: 
      camera-1: ['lidar-1', 'camera-1']
      imu-1: ['lidar-1','imu-1']  
      body-1: ['lidar-1', 'body-1']
      body-2: ['lidar-1', 'body-2']

  imu-1:
    intrinsic: ''
    extrinsic:
      lidar-1: ['imu-1', 'lidar-1']
      camera-1: ['imu-1', 'camera-1']
  
  body-1:
    intrinsic: ''
    extrinsic: 
      camera-1: ['body-1', 'camera-1']
      
  body-2:
    intrinsic: ''
    extrinsic: 
      camera-1: ['body-2', 'camera-1']
